name: Deploy Github Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
  id-token: write
  pages: write
jobs:
  build_mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: mkdocs build --strict
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'
      - uses: actions/deploy-pages@v4
