name: Deploy Github Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build_mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
